### ISSUE TITLE
[First Issue!] Remove Binary blobs and node_modules

### ISSUE THREAD

**Issue by Weather-OS** [ItsDrCat/ObsidianMC#1]
If the NJS project can be replicated in a local environment there’s no point in shipping the `node_modules` directory and `Obsidian.exe`.

Remove them from this GitHub Repository. This will save both storage space and reduce cloning times.

**Comment by ItsDrCat** [comment]
I’ll have to make a .gitignore for the node_modules directory, but I’ll try to remove all of the excess files when I first can.

**Comment by jasonjgardner** [comment]
@ItsDrCat 
> I’ll have to make a .gitignore for the node_modules directory, but I’ll try to remove all of the excess files when I first can.

Your .gitignore:
```.gitignore
*.exe
node_modules
```
In your terminal:

```bash
git rm -r node_modules/
git rm Obsidian.exe
```

Then you'll need to commit these changes, create a release, and upload the .exe as an attachment when it's time to distribute. You'll probably want to look into `git rebase` too.
