### ISSUE TITLE
It just immediately when i try to launch it :(

### ISSUE THREAD

**Issue by ImJustASceneQueenX3** [ItsDrCat/ObsidianMC#3]
idk what else to say like instantly closes :(

**Comment by ABUCKY0** [comment]
Right click on the folder, click "open in terminal", then run `./Obsidian.exe`, it should show any errors that appear. Send those here please.

**Comment by ItsDrCat** [comment]
Issue is caused from “tempimg” folder missing in latest release. For the time being just create a new folder and call it “tempimg” and that should fix the issue. (I will also update the bugged release when I next can)
