### ISSUE TITLE
i cant setup a pack

### ISSUE THREAD

**Issue by aaa6675000** [ItsDrCat/ObsidianMC#4]

**Comment by aaa6675000** [comment]
when i type "QuickSetupPack" it closes immediately

**Comment by ItsDrCat** [comment]
When you run QuickSetupPack does it ask another question and then close, or does it just close the moment you type “QuickSetupPack”

**Comment by aaa6675000** [comment]
It closes without any other question

**Comment by ItsDrCat** [comment]
Open the Obsidian folder in the terminal and then run `./Obsidian.exe`.
If you run QuickSetupPack it should give you an error message instead of closing. If this does work please copy the error message here. :D

**Comment by aaa6675000** [comment]
where is the terminal

**Comment by aaa6675000** [comment]
sorry but its my first time trying obsidian

**Comment by aaa6675000** [comment]
nvm
i found the terminal

**Comment by aaa6675000** [comment]
Obsidian
QuickSetupPack
QuickSetupPack-D
ImportGenerationData
√ What do you want to do? (Choices listed above) ... QuickSetupPack
node:fs:1513
  const result = binding.readdir(
                         ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\albar\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\resource_packs'
    at Object.readdirSync (node:fs:1513:26)
    at index.js:483:8
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'C:\\Users\\albar\\AppData\\Local\\Packages\\Microsoft.MinecraftUWP_8wekyb3d8bbwe\\LocalState\\games\\com.mojang\\resource_packs'
}

Node.js v21.5.0

**Comment by aaa6675000** [comment]
this it the error

**Comment by aaa6675000** [comment]
i think i know the issue 
my user file location is called albar.DESKTOP-V5QGJRT and obsidian is trying to access the wrong one because windows somehow thinks that albar.DESKTOP-V5QGJRT is my user file location but my real user file is albar and i dont know how to rename the albar.DESKTOP-V5QGJRT to just albar

**Comment by ItsDrCat** [comment]
Put Obsidian in your C: drive and make sure you have a folder called “tempimg”. (If you are missing a folder called “tempimg” within Obsidian, just create a folder with that name)

**Comment by aaa6675000** [comment]
still

**Comment by aaa6675000** [comment]
not working

**Comment by ItsDrCat** [comment]
Is Minecraft installed on your C: drive or is it on something else?

**Comment by aaa6675000** [comment]
oh

**Comment by aaa6675000** [comment]
i think its on G: drive

**Comment by ItsDrCat** [comment]
Ah, the issue is that Obsidian only checks the C: drive right now. In the next update I’ll add a setting that allows you to change which drive is checked.

**Comment by aaa6675000** [comment]
ok
thanks for help

**Comment by aaa6675000** [comment]
you are my best modder and continue updating catrtx
