### ISSUE TITLE
Obsidian not opening

### ISSUE THREAD

**Issue by Tortida** [ItsDrCat/ObsidianMC#6]
Everytime I try to open Obsidian it just gives an error screen for a frame and closes.
![Captura de tela 2024-09-14 174531](https://github.com/user-attachments/assets/66a4eec5-a196-431b-995f-589711c38269)

**Comment by ItsDrCat** [comment]
https://github.com/ItsDrCat/ObsidianMC/issues/3

**Comment by Tortida** [comment]
ok thx
